languageCode = "en-us"
baseurl = "http://interiorspecialties.net/"
title = "Interior Specialties"
theme = "interiorspecialties"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-1446018-12"

[params]
	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "Interior Specialties"
	description = "(614) 882-7733 rick@interiorspecialties.net"

	# Link custom assets relative to /static
	custom_css = []
	custom_js  = []

	# Possibility to disable external/additional fonts
	# Exception: Fontawesome
	disableFonts = false

	# 404 error customization
	[params.error404]
		heading = "Page couldn't be found"
		text = "Please visit [this page](/)"

	# Optional piwik tracking
	#[params.analytics.piwik]
	#  URL = "https://stats.example.com"
	#  ID = "42"
	#  # Track all subdomains with "*.example.com"
	#  domain = "www.example.com"
	#  # Optional integrity check hash
	#  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

	# Navigation
	[params.navigation]
		brand = "Interior Specialties"
		# Optional logo as brand stored in img/
		#logo = "logo.svg"
		contact = "Contact"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Manufacturer's Representatives located in Columbus, Ohio"
		buttonText = "Tell me more"

	[params.about]
		title = "About Interior Specialties"

	# Services section

	# Contact section
	[params.contact]
		enable = true
		title = "Contact us"
		# subtitle  = "Want to know about these products or get a quote? We would love to hear from you."
		buttonText = "Send message"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!

		# It is possible to substitute formspring with other providers
		# as an example the mailout plugin from caddy.
		# Provide the post URL for the form and depending on the provider
		# add some custom JS script to finish the implementation.
		# postURL = "https://example.com/mailout/"

		email = "rick@interiorspecialties.net"

		# Success and error message overwrite for async contact form
		#thanks = "Thank you for awesomely contacting us."
		#error = "Message could not be send. Please contact us at mail@example.com instead."

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."

			# Add optional form fields to identify contact forms
			#[[params.contact.form.hidden]]
			#  name = "someID"
			#  value = "example.com"
			#
			#[[params.contact.form.hidden]]
			# Special values for name such as "page" and "site" will be autofilled
			#  name = "page"

	# Footer section
	[params.footer]
		enable = true
		copyright = "Copyright &copy;2020 Interior Specialties"

		[[params.footer.quicklinks]]
			text = "1-614-882-7733"
			link = "tel:16148827733"

		[[params.footer.quicklinks]]
			text = "rick@interiorspecialties.net"
			link = "mailto:rick@interiorspecialties.net"
