languageCode = "en-us"
baseurl = "http://interiorspecialties.net/"
title = "Interior Specialties"
theme = "interiorspecialties"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-1446018-12"

[params]
	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "Interior Specialties"
	description = "Interior Specialties is a manufacturer’s representative agency that serves Central and Southern Ohio through the promotion and sale of a variety of specialty interior building products – products that are used by commercial contractors and facility owners/operators within commercial, health-care and educational buildings"

	# Link custom assets relative to /static
	custom_css = []
	custom_js  = []
	favicon    = "favicon.ico"

	# Possibility to disable external/additional fonts
	# Exception: Fontawesome
	disableFonts = false

	# 404 error customization
	[params.error404]
		heading = "Page couldn't be found"
		text = "Please visit [this page](/)"

	# Optional piwik tracking
	#[params.analytics.piwik]
	#  URL = "https://stats.example.com"
	#  ID = "42"
	#  # Track all subdomains with "*.example.com"
	#  domain = "www.example.com"
	#  # Optional integrity check hash
	#  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

	# Navigation
	[params.navigation]
		brand = "Interior Specialties"
		# Optional logo as brand stored in img/
		#logo = "logo.svg"
		acrovyn = "Acrovyn"
		pedisystems = "PediSystems"
		generalcubicle = "Cubicle Track / Curtains"
		contact = "Contact"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Representing Construction Specialties since 1985"
		buttonText = "Tell me more"

	[params.about]
		title = "About Interior Specialties"

	# Services section
	[params.acrovyn]
		enable = true
		title = "Acrovyn Products"

		[[params.acrovyn.row]]

		[[params.acrovyn.row.list]]
			icon = "callout-acrovyn-wall-protection.gif"
			title = "Acrovyn Walls"
			description = "Wave goodbye to damage and say hello to stunning environments with our Acrovyn interior wall protection products."
			url = "http://www.c-sgroup.com/acrovyn"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn High-Impact Wall Covering"
				link = "http://www.c-sgroup.com/acrovyn/wall-covering"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Wall Panels"
				link = "http://www.c-sgroup.com/acrovyn/wall-panels"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Handrails"
				link = "http://www.c-sgroup.com/acrovyn/handrails"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Crashrails"
				link = "http://www.c-sgroup.com/acrovyn/crash-rails"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Corner-Guards"
				link = "Acrovyn Corner-Guards"

			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Door & Door-Frame Protection"
				link = "http://www.c-sgroup.com/acrovyn/door-covering"

		[[params.acrovyn.row.list]]
			icon = "callout-acrovyn-doors.gif"
			title = "Acrovyn Doors"
			description = "Virtually indestructible Acrovyn Doors were designed to withstand daily traffic and wear without sacrificing aesthetics and design."
			url = "http://www.c-sgroup.com/acrovyn-doors"

			[[params.acrovyn.row.list.links]]
				text = "View Acrovyn Door Product Video"
				link = "http://www.c-sgroup.com/acrovyn-doors/movie-promotion"
			[[params.acrovyn.row.list.links]]
				text = "Acrovyn Door Selector"
				link = "http://www.c-sgroup.com/acrovyn-doors/door-selector"

		# About section
	[params.pedisystems]
		enable = true
		title = "PediSystems Products"

		[[params.pedisystems.row]]

		[[params.pedisystems.row.list]]
			icon = "callout-pedisystems.gif"
			title = "PediSystems Entrance Flooring"
			description = "C/S Pedisystems architectural mats and grids keep the entrances of commercial buildings, schools and hospitals, safe and beautiful by stopping dirt, snow and water at the door."
			url = "http://www.c-sgroup.com/entrance-flooring/entrance-mats-entrance-grids"

			[[params.pedisystems.row.list.links]]
				text = "View PediSystems Product Video"
				link = "http://www.c-sgroup.com/entrance-flooring/promo-movie"

			[[params.pedisystems.row.list.links]]
				text = "PediTred"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-grids/peditred_g4"

			[[params.pedisystems.row.list.links]]
				text = "PediGrid"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-grids/pedigrid_g1"

			[[params.pedisystems.row.list.links]]
				text = "GridLine"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-grids/gridline_g6"

			[[params.pedisystems.row.list.links]]
				text = "PediMat"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-mats/pedimat_m1"

			[[params.pedisystems.row.list.links]]
				text = "TreadLine"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-mats/treadline_t1"

			[[params.pedisystems.row.list.links]]
				text = "DesignStep"
				link = "http://www.c-sgroup.com/entrance-flooring/design-step"

			[[params.pedisystems.row.list.links]]
				text = "DuroMat"
				link = "http://www.c-sgroup.com/entrance-flooring/entrance-mats/duromat_dm"

			[[params.pedisystems.row.list.links]]
				text = "Floorometry"
				link = "http://www.c-sgroup.com/floorometry/tech-center"

			[[params.pedisystems.row.list.links]]
				text = "View Floorometry Product Video"
				link = "http://www.c-sgroup.com/floorometry/promo-movie"



	# Team section
	[params.generalcubicle]
		enable = true
		title = "General Cubicle"

		[[params.generalcubicle.row]]

		[[params.generalcubicle.row.list]]
			icon = "callout-general-cubicle-track-and-curtain.gif"
			title = "Curtains and Track"
			description = "C/S General Cubicle manufacturers the industry's finest line of flame-resistant privacy curtains, tracks and track accessory items."
			url = "http://www.c-sgroup.com/cubicle-track-curtains"

		[[params.generalcubicle.row.list.links]]
			text = "Track"
			link = "http://www.c-sgroup.com/cubicle-track-curtains/track_systems"

		[[params.generalcubicle.row.list.links]]
			text = "Carriers"
			link = "http://www.c-sgroup.com/cubicle-track-curtains/track_carriers"

		[[params.generalcubicle.row.list.links]]
			text = "IV Carriers"
			link = "http://www.c-sgroup.com/cubicle-track-curtains/iv_pendants"

		[[params.generalcubicle.row.list.links]]
			text = "Curtains"
			link = "http://www.c-sgroup.com/cubicle-track-curtains/fabric"

	# Contact section
	[params.contact]
		enable = true
		title = "Contact us"
		subtitle  = "Want to know about these products or get a quote? We would love to hear from you."
		buttonText = "Send message"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!

		# It is possible to substitute formspring with other providers
		# as an example the mailout plugin from caddy.
		# Provide the post URL for the form and depending on the provider
		# add some custom JS script to finish the implementation.
		# postURL = "https://example.com/mailout/"

		email = "rick@interiorspecialties.net"

		# Success and error message overwrite for async contact form
		#thanks = "Thank you for awesomely contacting us."
		#error = "Message could not be send. Please contact us at mail@example.com instead."

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."

			# Add optional form fields to identify contact forms
			#[[params.contact.form.hidden]]
			#  name = "someID"
			#  value = "example.com"
			#
			#[[params.contact.form.hidden]]
			# Special values for name such as "page" and "site" will be autofilled
			#  name = "page"

	# Footer section
	[params.footer]
		enable = true
		copyright = "Copyright &copy; 2017 Interior Specialties"

		[[params.footer.quicklinks]]
			text = "Product Literature"
			link = "#"
